version: '3'

services:
        systembinsh:
                restart: always
                build: ./
                read_only: true
                networks:
                        - internal
        proxy_0:
                restart: always
                image: nginx
                ports:
                        - '30000:30000'
                volumes:
                        - ./build/nginx.conf:/etc/nginx/nginx.conf:ro
                networks:
                        - default
                        - internal
                depends_on:
                        - systembinsh

networks:
        default:
        internal:
                internal: true
